name: "Reduced set of tests for push events"
on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          pip install poetry==1.8.2
          pip install poetry-plugin-export==1.7.0
      - name: Install Nox
        run: |
          pip install nox==2024.03.02
          pip install nox-poetry==1.0.3
      - name: Run tests
        run: nox --non-interactive --error-on-missing-interpreter --session "tests-${{ matrix.python-version }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Poetry
        run: |
          pip install poetry==1.8.2
          pip install poetry-plugin-export==1.7.0
      - name: Install Nox
        run: |
          pip install nox==2024.03.02
          pip install nox-poetry==1.0.3
      - name: Lint
        run: nox --non-interactive --error-on-missing-interpreter --session "precommit"
